### ISSUE TITLE
Using rlua for modding

### ISSUE THREAD

**Issue by TheNeikos** [amethyst/rlua#118] opened 2019-02-04 22:37 UTC
First of all, thank you for the work on this crate. It's amazing that there is some way of harnessing Lua in a Rust program safely.

However, that's where the problems then usually come in, Rust has the borrow checker and it makes sure you don't do stupid things. And I guess I'm not smart/knowledgeable enough to bend/adapt my ideas to the lifetime and API requirements of `rlua`.

What I try to do seems 'conceptually' simple: I want to write an exoskeleton of rules in Rust, and let Lua fill in the gaps, like behaviors etc...

To illustrate I mean something like this:
```
game::createFoo(1, "Foobar")

game::addNewNPC("My NPC", 1, {some = "arbitrary", data = 2}, function() {})
```

The idea would be then to use this user-defined behavior on the Rust side.

Now, on the Rust side, I planned on creating a `UserData` with the methods above: `createFoo` and `addNewNPC`. However, I quickly ran into either Lifetime issues: I cannot create a struct that borrows, while also using `UserData::add_methods`, as the trait signature requires `add_methods<'lua, ....` thus forcing it's _own_ lifetime, meaning I can never satisfy the outer lifetime.

Nor can I use `AnyUserData` to associate the one `Table<'a>` with it, as `add_method` doesn't give me `AnyUserData` back.

Now to my questions:

Have you encountered such a situation before? If yes, what kind of code structure did you use? Or is this maybe something that rlua cannot do? Or am I completely misunderstanding what rlua is for?

Thank you for your time!

**Comment by kyren** [comment] 2019-02-04 22:53
> Have you encountered such a situation before

Yes, you should look at Context::scope to create userdata that isn’t ‘static.  It comes with some limitations (and is currently not the fastest thing in the world), but it allows you to keep references in userdata and is designed specifically for this.

**Comment by TheNeikos** [comment] 2019-02-05 06:20
Is there maybe a way to add a lifetime to UserData in a way that would allow this?

Maybe something like: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f2b87e225e97c9c6f54761cea5a1bfac

This would allow one to store lua data in a struct that could be constructed in a scope I think. What do you think?

**Comment by kyren** [comment] 2019-02-05 12:30
> Is there maybe a way to add a lifetime to UserData in a way that would allow this?

> This would allow one to store lua data in a struct that could be constructed in a scope I think. What do you think?

I'm a bit confused at your question, [this is already possible](https://github.com/kyren/rlua/blob/e351bf57fa4c3985109d6674a8b6c35f9890da16/tests/scope.rs#L108), it's what `Scope::create_nonstatic_userdata` was designed to do.

You shouldn't need to make any changes to the `UserData` trait.  Maybe I'm misunderstanding the question?

(That example I linked is in the tests and it's not *great*, but it's the best existing example I could find.  I should probably have a real example of this in the documentation somewhere.  For example, the test for *some* reason uses `Cell`, but this is not required and has nothing to do with using `Scope::create_nonstatic_userdata`, I don't even remember why the test uses `Cell` exactly.)

**Comment by TheNeikos** [comment] 2019-02-05 12:51
My problem is different, insofar that I cannot add a bound involving the `'lua` lifetime. (Since Rust forces signature of trait methods to be exactly the same) 

In the example I linked, you can see that in line 33. Without that line, Rust doesn’t know that the lifetime, of for example `Table<'lua>`, is just as long as the struct’s lifetime and thus can’t be assigned.

**Comment by kyren** [comment] 2019-02-05 13:54
Okay, I understand what you're asking now, and I see what you were doing in the example you linked.

The change you're proposing for `UserData` is not sound.  It would allow you to capture parameters inside the `UserData` (which it seems is what you're explicitly *trying* to do), and these parameters would have pointers to `lua_State` which may have expired.  You cannot hold onto a `Context<'lua>` inside a Lua userdata, the `'lua` lifetime does not mean "lives as long as the interpreter", it means "lives as long as some specific `*mut lua_State` is valid".

Why this is and how this is safe is all horribly complicated and brittle, but is briefly described in the source to `Scope`, (here and in other places):
https://docs.rs/rlua/0.16.2/src/rlua/scope.rs.html#151

> Without that line, Rust doesn’t know that the lifetime, of for example `Table<'lua>`, is just as long as the struct’s lifetime and thus can’t be assigned.

That's the problem, it's not as long as the struct's lifetime.  a `Context<'lua>` is only valid within a single callback, the `lua_State` may be, for example, a Lua coroutine thread.

If the userdata you're making needs only to store Lua values (and not *also* references to Rust types), you can use the `set_user_value` / `get_user_value` feature of `AnyUserData` to store them, and then instead of `UserDataMethods::add_method`, use `UserDataMethods::add_function`.  This takes a callback that accepts as its first parameter an `AnyUserData` handle which is guaranteed to contain your `T: UserData` type rather than a straight `&T`, but since it gives you the `AnyUserData` handle instead, you can call `AnyUserData::get_user_value` on it.  This is the specific reason that this API exists.

If you need to need to store an internal handle type *and* a reference to some Rust type as well, then you'll have to use `Scope::create_nonstatic_userdata`.  Since an `AnyUserData` handle is of limited use here, what you can do is store an *outer* handle type in your userdata.  However, you will still not be able to capture parameters and replace that handle value, because the outer `'lua` and inner `'lua` lifetimes will not be the same.  This is a good thing, because it would still be dangerous to capture such parameters inside your userdata, in fact this specific thing has come up before in #82 and was a soundness issue.  (Now that I thought about it some more, I remember the situation here, and this is actually not very useful *at all* to do.  Since the two `'lua` lifetimes are invariant and different, you can't combine stored handles with callback handles *at all*, so it's basically pointless to do this.  I had to read my own comments in #97 to remember the details here)

If you need to have both the ability to have an external reference to a Rust type *and* the ability to capture Lua values and store them in your type, then you might run into difficulty.  One solution here is, instead of trying to capture associated values with `AnyUserData::[get,set]_user_value`, you can just use registry values instead.  This is in general not really a good idea to do with userdata since you'll defeat the borrow checker, but with *scoped* userdata this is often fine (since the userdata won't live past the scope anyway).  If you genuinely need Rust references + stored handles in a `UserData` type, this might be your best bet (though there are usually easier ways to do what you want by changing your Lua API or using Lua-side wrappers to your API).

This may all sound extremely confusing, and that's because it is.  The issues here are incredibly subtle and easy to get wrong.  One *possible* improvement that I can think of would be to somehow provide a special API just for non-static userdata where *both* the type reference *and* the `AnyUserData` handle are given, to support specifically the case where you need non-static userdata with associated user values.  The use for this though is incredibly, incredibly niche so I'm not sure how much it would be worth it vs. the increase in complexity of an already complex API.

**Comment by TheNeikos** [comment] 2019-02-05 14:10
I understand. That is indeed incredibly tricky. I am wondering though in what kind of scope rlua is to be used then? (I am genuinely curious, just so I can understand what is possible, or if I maybe need another tech)

Since if I can’t use lua-supplied data rlua feels very restricted in terms of interop.

Thank you for your time answering my questions!

**Comment by kyren** [comment] 2019-02-05 14:46
> I understand. That is indeed incredibly tricky. I am wondering though in what kind of scope rlua is to be used then? (I am genuinely curious, just so I can understand what is possible, or if I maybe need another tech)

> Since if I can’t use lua-supplied data rlua feels very restricted in terms of interop.

I feel like we might be talking past each other, you can use Lua-supplied data in lots of ways, in every way I can possibly make safe.

You're not actually even *able* to store Lua values inside userdata via the plain Lua C API.  This limitation is not an invention of `rlua`, this is why things like [lua_setuservalue](
https://www.lua.org/manual/5.3/manual.html#lua_setuservalue) exist in the first place (and why this is exposed via `AnyUserData::set_user_value`.

The Lua C API does not even give you the ability to store values generally at all.  You only have access at any given time to a stack which is only really valid for the context of a single callback.  To store values longer term, you're supposed to use the registry via `luaL_ref` / `luaL_unref`, which is exposed in `rlua` via `Context::create_registry_value`.  In languages with destructors like Rust, this is often made easier by automatically freeing on drop.  (This works fine until you place one of these handle values inside a userdata, at which point you can easily make an unbreakable gc cycle, which is the reason for the scare language in the documentation of `RegistryKey`.  `lua_setuservalue` doesn't have this problem since the garbage collector is aware of the associated user values)

Basically all of the limitations of `rlua` come from the API that it sits on top of, or more generally they come from the inherent difficulty of binding two languages together with different garbage collection systems.

What is it that you'd like to do that you can do from the Lua C API but not from rlua?  Certainly there are some things left that you still can't do like using continuations (`lua_yieldk`, `lua_pcallk`) and yielding directly from callbacks, but most everything else that you would want to do currently works.

If you just really want to store values inside a userdata in a very unrestricted way, use registry handles.  If one of those values in turn references the userdata itself, this will be a gc cycle that the Lua gc cannot break (due to it not understanding the registry handle pattern).  If that is unacceptable, use `AnyUserData::set_user_value` to add associated data that the Lua gc does understand.  If you need to store more than *one* value, set the associated user value to a table (Lua 5.4 adds the ability to store more than one associated user value, but Lua 5.4 is not yet released, and you can always just use a table).

There's not really anything else you can do, even with access to the C API.  `rlua` is trying very hard to allow you to do everything you might want to do that is safe, and nothing that isn't, is there something that it's failing at that I'm unaware of?

**Comment by TheNeikos** [comment] 2019-02-05 22:24
> There's not really anything else you can do, even with access to the C API. `rlua` is trying very hard to allow you to do everything you might want to do that is safe, and nothing that isn't, is there something that it's failing at that I'm unaware of?

No, I think that I am just not understanding how Lua/Rust interop works and am assuming things that aren't possible.

Here is what I tried to do:

I use a Lua Script that adds new objects to a vector of available cards.
I wanted the Card object to have a table of arbitrary values, and a table of callbacks.

I was experimenting with something likes this:
```rust
struct Card<'a> {
    infos: Table<'a>,
    id: String,
    ...etc
}

impl<'a> LuaUserData for Game<'a> {
    fn add_methods<'lua, M: rlua::UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method_mut("addCard", |_, this, args: (String, String, String, LuaTable<'lua>)| {
            let (id, name, text, infos) = args;
            this.cards.push(Card::new(id, name, text, infos));
            Ok(())
        });
    }
}
```
The idea is to have the callbacks defined in Lua so that one can easily add new cards and make simple changes. But as you can see, I cannot do this because of the issue you outlined above.

Even when using `set_user_value` I am not sure how this would work with for example a `Vec`.

But I haven't used `rlua` before so I am certain I'm trying to force some imaginary projected API on the actual restrictions. Which is why I am very grateful for your answers :heart:

**Comment by kyren** [comment] 2019-02-06 00:55
I really need to revisit #87 soon, as these are the exact sorts of things that tend to come up if you haven't used Lua in another context before and don't already have a good idea of what the vanilla Lua C API does and doesn't provide.

This isn't your fault at all, and what you want to do isn't at all unreasonable, but there are some limitations that you're running into which currently don't have great answers in *any* Lua bindings system.

> I use a Lua Script that adds new objects to a vector of available cards.
> I wanted the Card object to have a table of arbitrary values, and a table of callbacks.

So, the problem you're running into is, fundamentally, that you want Lua to own a Rust userdata which owns Lua values.  You probably do not want to do this...

The Lua C API doesn't actually provide any concept of a "handle" to a value, or allow C to really "own" values at all.  The Lua C API actually does its best to protect its user from its own garbage collector, so the API doesn't really tend to give out pointers to things like tables.  There is no way to tell the Lua C API, give me a pointer to this table, and I will tell you when I'm done with it and you can garbage collect it.  Instead, what you get is that a table exists in the Lua "stack" and you operate on it through an index into this stack.  You can think of values like `rlua::Table`, `rlua::String`, etc as a tuple of `(<current Lua stack>, <index on that stack>)`, so if you get such a value inside a callback, it's only valid *for that callback*.  After the callback ends, the stack frame for that callback goes away, so Lua is free to garbage collect any values that were previously owned by it.

(This is not actually how the handle values work, for reasons that aren't important, but at one time they did actually work like this).

So how does the Lua C API let you store values for any length of time then?  Well, it gives you a magic, global table, only available from C called "the registry".  You can set values in this table with any valid table key, so you can either set named values like with a string key, or you can use functions like [luaL_ref](
https://www.lua.org/manual/5.3/manual.html#luaL_ref) to produce unique integer keys for this table.  In this way, you can take your temporary value in a Lua stack, place it into the registry with an auto-generated key, *keep the key*, and then when you need the value later, go look it up again in the global registry.  The Lua registry is truly global, it's shared across the entire Lua state, so you have to be careful not to conflict with anything else using the same Lua state, which is why there is a system for auto-generating integer keys.

When you get a handle value as a parameter to a callback, it has a lifetime that keeps you from accidentally keeping it around.  The reason that you can't keep these handles around is that they don't live forever, they're (morally) indexes into a stack which is going to be popped off of when the callback returns, or even deleted entirely in the case of things like coroutines.  Lua itself protects the user from the garbage collector and doesn't let the user of the API participate in garbage collection like you might be thinking, because making a systems language API work with a garbage collector is *very hard*.  If you want to keep those values around for a length of time, then `rlua` provides an API to do this, you pass the value into something like [create_registry_value](https://docs.rs/rlua/0.16.2/rlua/struct.Context.html#method.create_registry_value) and you get back a registry key, and this key is 'static + Send + Sync.  You can store it *anywhere*, even inside userdata if you want.

The *problem* you'll run into if you do that you can very easily make a garbage collector cycle.  In your example, if your Game owns a Lua function via a registry handle, and that Lua function closes over your Game object, without external intervention, those two objects will *never be garbage collected* until the main Lua state is dropped in Rust.  How could they?  Lua sees that the Lua function is owned by the global registry table, and it sees that the Game userdata is owned by the function, and that's all it sees.  There is no way to tell Lua that really, the entry in the global registry table only exists to point from the Game userdata to the function, so it can collect both as a cycle.

The designers of the Lua C API realized this was a problem, so they provide an escape hatch.  It's so incredibly useful to be able to store C values with Lua values, that there's a special associated "slot" with Lua userdata where you can add references to Lua values that are garbage collected.  This is what is exposed via [AnyUserData::set_user_value](
https://docs.rs/rlua/0.16.2/rlua/struct.AnyUserData.html#method.set_user_value).  It's not *ergonomic*, but it allows you to keep C data + Lua data as a garbage collected pair.

So for your specific example, what are your options?  Well, one option is that you could just decide to *not care* about the gc cycle issue, and write this:

```
struct Card {
    infos: LuaRegistryKey,
    id: LuaRegistryKey,
    ...etc
```

Since you're using an `rlua::RegistryKey`, your type will be static and can easily be placed inside userdata.  This might not ever get *garbage collected* because of the above issues, but if you don't care about that or just know to be careful in your Lua scripts, this is an option.

Another option is to keep a `Table` around with all the Lua-side data that your game might need to store, and store that `Table` as the "user value" associated with your userdata via `AnyUserData::set_user_value`.  You would need to keep all of the Lua data that a game might hold inside this table, but if you did this then you could have a `Game` userdata that was always correctly garbage collected.

(Something I hadn't thought about until now, but it might be useful to expose `luaL_ref` / `luaL_unref` via `rlua::Table`, so in that way if you wanted you could actually have kind of your own per-userdata "registry" for associated values.  Or perhaps there is a nice API that I can provide on top of `AnyUserData` which allows arbitrary numbers of associated values, or something like this.  There's room for ergonomic improvement here, even if it doesn't fundamentally allow you to do anything new.)

Another option is to re-structure your API so that the `Game` userdata doesn't need to keep Lua values at all.  Another option is to re-structure your API so that Lua doesn't need to *own* `Game`, and therefore you can't run afoul of the garbage collector by `Game` owning registry handles.  Yet another option might be to accept that `Game` is a Lua global, and possibly use named values in the Lua registry to store different globally available game state (I'm not sure about how this might look, it depends on what your API looks like of course).  There are a lot of ways to bake this cake.

I know this is potentially a lot more information than you really wanted, but language boundaries are very often difficult and full of nuance and gotchas.  Ideally, we'd simply be able to write Rust types and hold pointers to Lua data and everything would Just Work, but such an API would require deep integration with a garbage collector that vanilla Lua simply does not provide.  I'm currently doing research on how to make the situation better via my own Lua interpreter project, but it's still extremely early and I don't think I have a clear picture yet of exactly how I'll allow arbitrary userdata there either, and the deeply integrated garbage collector comes with its own set of problems.  Maybe soon I'll have a better answer here.

This is probably the number one thing that needs to go in the FAQ, but the problem is that the full explanation is really not very FAQ length 😐.

**Comment by TheNeikos** [comment] 2019-02-06 15:52
Wow, okay that is an amazing writeup. I see now why I can't keep values after a callback is done. Thank you very much :smile: 

In my specific case, the `game` object would live for the whole duration of a game. So if I drop the main `Lua` state, this will just get removed if I understand correctly.

I've thought about using a message passing style to communicate with lua, so luckily that should work with what you've told me.


PS: I'm still amazed that you managed to get this to work this far without it crashing all the time, given the amount of corner cases there must be, thank you!

**Comment by kyren** [comment] 2019-02-06 22:07
> In my specific case, the `game` object would live for the whole duration of a game. So if I drop the main `Lua` state, this will just get removed if I understand correctly.

Yeah, all objects are definitely dropped at destruction time regardless of reachability inside the Lua state.

I mentioned this briefly before, but another option is that if you use a *scoped* userdata, generally you don't care about whether it contains registry keys because scoped functions / userdata are forcibly dropped at the end of the scope.  Might help?

**Comment by jugglerchris** [comment] 2021-06-28 07:20
Closing as I believe this has been answered.

**Closed by jugglerchris** 2021-06-28 07:20 UTC
